[project]
name = "fusion-pixel-font"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bdfparser>=2.2.0",
    "ptpython>=3.0.29",
]
